// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vriscv_top.h for the primary calling header

#ifndef VERILATED_VRISCV_TOP_RISCV_CORE__S1_H_
#define VERILATED_VRISCV_TOP_RISCV_CORE__S1_H_  // guard

#include "systemc"
#include "verilated_sc.h"
#include "verilated.h"
class Vriscv_top_biriscv_csr__SB0;
class Vriscv_top_biriscv_issue;


class Vriscv_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vriscv_top_riscv_core__S1 final : public VerilatedModule {
  public:
    // CELLS
    Vriscv_top_biriscv_csr__SB0* u_csr;
    Vriscv_top_biriscv_issue* u_issue;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst_n,0,0);
        VL_IN8(__PVT__mem_d_accept_i,0,0);
        VL_IN8(__PVT__mem_d_ack_i,0,0);
        VL_IN8(__PVT__mem_d_error_i,0,0);
        VL_IN8(__PVT__mem_i_accept_i,0,0);
        VL_IN8(__PVT__mem_i_valid_i,0,0);
        VL_IN8(__PVT__mem_i_error_i,0,0);
        VL_IN8(__PVT__intr_i,0,0);
        VL_OUT8(__PVT__mem_d_rd_o,0,0);
        VL_OUT8(__PVT__mem_d_wr_o,3,0);
        VL_OUT8(__PVT__mem_d_cacheable_o,0,0);
        VL_OUT8(__PVT__mem_d_invalidate_o,0,0);
        VL_OUT8(__PVT__mem_d_writeback_o,0,0);
        VL_OUT8(__PVT__mem_d_flush_o,0,0);
        VL_OUT8(__PVT__mem_i_rd_o,0,0);
        VL_OUT8(__PVT__mem_i_flush_o,0,0);
        VL_OUT8(__PVT__mem_i_invalidate_o,0,0);
        CData/*0:0*/ __PVT__branch_d_exec1_request_w;
        CData/*0:0*/ __PVT__csr_opcode_valid_w;
        CData/*0:0*/ __PVT__branch_csr_request_w;
        CData/*0:0*/ __PVT__mul_opcode_valid_w;
        CData/*0:0*/ __PVT__csr_opcode_invalid_w;
        CData/*5:0*/ __PVT__csr_writeback_exception_w;
        CData/*0:0*/ __PVT__fetch1_instr_invalid_w;
        CData/*0:0*/ __PVT__fetch0_instr_rd_valid_w;
        CData/*0:0*/ __PVT__branch_request_w;
        CData/*0:0*/ __PVT__writeback_mem_valid_w;
        CData/*0:0*/ __PVT__fetch0_fault_fetch_w;
        CData/*0:0*/ __PVT__fetch1_fault_page_w;
        CData/*0:0*/ __PVT__lsu_stall_w;
        CData/*0:0*/ __PVT__branch_info_is_not_taken_w;
        CData/*0:0*/ __PVT__branch_info_is_taken_w;
        CData/*0:0*/ __PVT__branch_info_is_ret_w;
        CData/*0:0*/ __PVT__fetch1_instr_exec_w;
        CData/*0:0*/ __PVT__fetch0_instr_exec_w;
        CData/*0:0*/ __PVT__exec1_hold_w;
        CData/*0:0*/ __PVT__branch_info_is_jmp_w;
        CData/*0:0*/ __PVT__fetch1_instr_lsu_w;
        CData/*1:0*/ __PVT__branch_csr_priv_w;
        CData/*5:0*/ __PVT__writeback_mem_exception_w;
        CData/*0:0*/ __PVT__fetch1_instr_branch_w;
        CData/*0:0*/ __PVT__fetch0_valid_w;
        CData/*0:0*/ __PVT__fetch0_fault_page_w;
        CData/*0:0*/ __PVT__fetch0_instr_invalid_w;
        CData/*0:0*/ __PVT__fetch1_fault_fetch_w;
        CData/*0:0*/ __PVT__fetch1_valid_w;
        CData/*0:0*/ __PVT__branch_d_exec0_request_w;
        CData/*0:0*/ __PVT__lsu_opcode_valid_w;
        CData/*0:0*/ __PVT__fetch1_instr_rd_valid_w;
        CData/*0:0*/ __PVT__branch_info_is_call_w;
        CData/*0:0*/ __PVT__fetch1_instr_mul_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__fetch_valid_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__fetch_fault_page_w;
        CData/*1:0*/ __PVT__u_frontend__DOT__fetch_pred_branch_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__fetch_fault_fetch_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__pred_taken_w;
        CData/*2:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_real_q;
        CData/*2:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_real_r;
        CData/*2:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_q;
        CData/*2:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_index_r;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_call_pred_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_ret_pred_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_valid_r;
    };
    struct {
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_upper_r;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_call_r;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_ret_r;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_jmp_r;
        CData/*4:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_entry_r;
        CData/*4:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_wr_entry_r;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_hit_r;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_miss_r;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT____VdfgRegularize_he46ab735_0_0;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT____VdfgRegularize_he46ab735_0_1;
        CData/*0:0*/ u_frontend__DOT__u_npc__DOT____VdfgRegularize_he46ab735_0_2;
        CData/*1:0*/ u_frontend__DOT__u_decode__DOT____Vcellinp__genblk1__DOT__u_fifo__info0_in_i;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__rd_ptr_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__wr_ptr_q;
        CData/*1:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__count_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__push_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop1_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop2_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pop_complete_w;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_55;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_56;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_57;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_58;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_59;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_60;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_61;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec0__DOT____VdfgRegularize_h27ba1afc_0_62;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_55;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_56;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_57;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_58;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_59;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_60;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_61;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_62;
        CData/*0:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_dec1__DOT____VdfgRegularize_h27ba1afc_0_63;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__active_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__icache_busy_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__stall_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__branch_q;
        CData/*1:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__branch_priv_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__branch_w;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__stall_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__icache_fetch_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__icache_invalidate_q;
        CData/*1:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__pred_d_q;
        CData/*0:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__skid_valid_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_rd_q;
        CData/*3:0*/ __PVT__u_lsu__DOT__mem_wr_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_cacheable_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_invalidate_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_writeback_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_flush_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_unaligned_e1_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_unaligned_e2_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_load_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_xb_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_xh_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_ls_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__pending_lsu_e2_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__issue_lsu_e1_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__complete_ok_e2_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__complete_err_e2_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__delay_lsu_e2_w;
    };
    struct {
        CData/*0:0*/ __PVT__u_lsu__DOT__load_inst_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__load_signed_inst_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__req_lh_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_unaligned_r;
        CData/*0:0*/ __PVT__u_lsu__DOT__mem_rd_r;
        CData/*3:0*/ __PVT__u_lsu__DOT__mem_wr_r;
        CData/*0:0*/ __PVT__u_lsu__DOT__dcache_flush_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__dcache_writeback_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__dcache_invalidate_w;
        CData/*0:0*/ __PVT__u_lsu__DOT__resp_load_w;
        CData/*0:0*/ u_lsu__DOT____Vcellinp__u_lsu_request__push_i;
        CData/*1:0*/ __PVT__u_lsu__DOT__addr_lsb_r;
        CData/*0:0*/ __PVT__u_lsu__DOT__load_byte_r;
        CData/*0:0*/ __PVT__u_lsu__DOT__load_half_r;
        CData/*0:0*/ __PVT__u_lsu__DOT__load_signed_r;
        CData/*0:0*/ __PVT__u_lsu__DOT__u_lsu_request__DOT__accept_o;
        CData/*0:0*/ __PVT__u_lsu__DOT__u_lsu_request__DOT__valid_o;
        CData/*0:0*/ __PVT__u_lsu__DOT__u_lsu_request__DOT__rd_ptr_q;
        CData/*0:0*/ __PVT__u_lsu__DOT__u_lsu_request__DOT__wr_ptr_q;
        CData/*1:0*/ __PVT__u_lsu__DOT__u_lsu_request__DOT__count_q;
        CData/*0:0*/ __PVT__u_mul__DOT__mulhi_sel_e1_q;
        CData/*0:0*/ __PVT__u_mul__DOT__mult_inst_w;
        CData/*0:0*/ __PVT__u_div__DOT__valid_q;
        CData/*0:0*/ __PVT__u_div__DOT__signed_operation_w;
        CData/*0:0*/ __PVT__u_div__DOT__div_operation_w;
        CData/*0:0*/ __PVT__u_div__DOT__div_inst_q;
        CData/*0:0*/ __PVT__u_div__DOT__div_busy_q;
        CData/*0:0*/ __PVT__u_div__DOT__invert_res_q;
        CData/*0:0*/ __PVT__u_div__DOT__last_div_q;
        CData/*0:0*/ __PVT__u_div__DOT__last_divu_q;
        CData/*0:0*/ __PVT__u_div__DOT__last_rem_q;
        CData/*0:0*/ __PVT__u_div__DOT__last_remu_q;
        CData/*0:0*/ __PVT__u_div__DOT__div_complete_w;
        CData/*3:0*/ __PVT__u_exec0__DOT__alu_func_r;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_r;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_taken_r;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_call_r;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_ret_r;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_jmp_r;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_taken_q;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_ntaken_q;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_call_q;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_ret_q;
        CData/*0:0*/ __PVT__u_exec0__DOT__branch_jmp_q;
        CData/*0:0*/ __PVT__u_exec0__DOT__u_alu__DOT__addsub_Ci;
        CData/*0:0*/ __PVT__u_exec0__DOT__u_alu__DOT__Co0;
        CData/*0:0*/ __PVT__u_exec0__DOT__u_alu__DOT__Co1;
        CData/*0:0*/ __PVT__u_exec0__DOT__u_alu__DOT__Co2;
        CData/*0:0*/ __PVT__u_exec0__DOT__u_alu__DOT__Co3;
        CData/*0:0*/ __PVT__u_exec0__DOT__u_alu__DOT__unused;
        CData/*3:0*/ __PVT__u_exec1__DOT__alu_func_r;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_r;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_taken_r;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_call_r;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_ret_r;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_jmp_r;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_taken_q;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_ntaken_q;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_call_q;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_ret_q;
        CData/*0:0*/ __PVT__u_exec1__DOT__branch_jmp_q;
        CData/*0:0*/ __PVT__u_exec1__DOT__u_alu__DOT__addsub_Ci;
        CData/*0:0*/ __PVT__u_exec1__DOT__u_alu__DOT__Co0;
        CData/*0:0*/ __PVT__u_exec1__DOT__u_alu__DOT__Co1;
    };
    struct {
        CData/*0:0*/ __PVT__u_exec1__DOT__u_alu__DOT__Co2;
        CData/*0:0*/ __PVT__u_exec1__DOT__u_alu__DOT__Co3;
        CData/*0:0*/ __PVT__u_exec1__DOT__u_alu__DOT__unused;
        CData/*0:0*/ __Vfunc_u_exec0__DOT__less_than_signed__0__Vfuncout;
        CData/*0:0*/ __Vfunc_u_exec0__DOT__greater_than_signed__1__Vfuncout;
        CData/*0:0*/ __Vfunc_u_exec1__DOT__less_than_signed__2__Vfuncout;
        CData/*0:0*/ __Vfunc_u_exec1__DOT__greater_than_signed__3__Vfuncout;
        CData/*0:0*/ __Vdly__u_lsu__DOT__mem_rd_q;
        CData/*3:0*/ __Vdly__u_lsu__DOT__mem_wr_q;
        CData/*0:0*/ __Vdly__u_lsu__DOT__mem_invalidate_q;
        CData/*0:0*/ __Vdly__u_lsu__DOT__mem_writeback_q;
        CData/*0:0*/ __Vdly__u_lsu__DOT__mem_flush_q;
        CData/*0:0*/ __Vdly__u_lsu__DOT__mem_unaligned_e1_q;
        CData/*0:0*/ __Vdly__u_div__DOT__div_busy_q;
        CData/*0:0*/ __Vdly__u_div__DOT__last_div_q;
        CData/*0:0*/ __Vdly__u_div__DOT__last_divu_q;
        CData/*0:0*/ __Vdly__u_div__DOT__last_rem_q;
        CData/*0:0*/ __Vdly__u_div__DOT__last_remu_q;
        VL_IN16(__PVT__mem_d_resp_tag_i,10,0);
        VL_OUT16(__PVT__mem_d_req_tag_o,10,0);
        SData/*8:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__global_history_real_q;
        SData/*8:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__global_history_q;
        SData/*15:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__u_lru__DOT__lfsr_q;
        SData/*15:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_right_fill_r;
        SData/*8:0*/ u_exec0__DOT__u_alu__DOT__u_adder32__DOT__u_adder8_1__DOT____VdfgRegularize_h91daf8aa_0_0;
        SData/*15:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_right_fill_r;
        SData/*8:0*/ u_exec1__DOT__u_alu__DOT__u_adder32__DOT__u_adder8_1__DOT____VdfgRegularize_h91daf8aa_0_0;
        VL_IN(__PVT__mem_d_data_rd_i,31,0);
        VL_IN(__PVT__reset_vector_i,31,0);
        VL_IN(__PVT__cpu_id_i,31,0);
        VL_OUT(__PVT__mem_d_addr_o,31,0);
        VL_OUT(__PVT__mem_d_data_wr_o,31,0);
        VL_OUT(__PVT__mem_i_pc_o,31,0);
        IData/*31:0*/ __PVT__fetch1_instr_w;
        IData/*31:0*/ __PVT__csr_writeback_exception_addr_w;
        IData/*31:0*/ __PVT__branch_info_pc_w;
        IData/*31:0*/ __PVT__mul_opcode_opcode_w;
        IData/*31:0*/ __PVT__branch_csr_pc_w;
        IData/*31:0*/ __PVT__mul_opcode_rb_operand_w;
        IData/*31:0*/ __PVT__mul_opcode_ra_operand_w;
        IData/*31:0*/ __PVT__lsu_opcode_ra_operand_w;
        IData/*31:0*/ __PVT__lsu_opcode_opcode_w;
        IData/*31:0*/ __PVT__fetch0_instr_w;
        IData/*31:0*/ __PVT__lsu_opcode_rb_operand_w;
        IData/*31:0*/ __PVT__branch_info_source_w;
        IData/*31:0*/ __PVT__csr_writeback_exception_pc_w;
        IData/*31:0*/ __PVT__u_frontend__DOT__fetch_pc_f_w;
        IData/*31:0*/ __PVT__u_frontend__DOT__fetch_pc_w;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_next_pc_w;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i3;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i4;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_next_pc_r;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i0;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i1;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__i2;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__i;
        IData/*28:0*/ u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT____VdfgRegularize_h8d0eb69c_0_1;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__branch_pc_q;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__branch_pc_w;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__pc_f_q;
        IData/*31:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__pc_d_q;
        VlWide<4>/*99:0*/ __PVT__u_frontend__DOT__u_fetch__DOT__skid_buffer_q;
        IData/*31:0*/ __PVT__u_lsu__DOT__mem_addr_q;
        IData/*31:0*/ __PVT__u_lsu__DOT__mem_data_wr_q;
    };
    struct {
        IData/*31:0*/ __PVT__u_lsu__DOT__mem_addr_r;
        IData/*31:0*/ __PVT__u_lsu__DOT__mem_data_r;
        IData/*31:0*/ __PVT__u_lsu__DOT__resp_addr_w;
        IData/*31:0*/ __PVT__u_lsu__DOT__wb_result_r;
        IData/*31:0*/ __PVT__u_lsu__DOT__u_lsu_request__DOT__i;
        IData/*31:0*/ __PVT__u_mul__DOT__result_e2_q;
        IData/*31:0*/ __PVT__u_mul__DOT__result_e3_q;
        VlWide<3>/*64:0*/ __PVT__u_mul__DOT__mult_result_w;
        IData/*31:0*/ __PVT__u_div__DOT__wb_result_q;
        IData/*31:0*/ __PVT__u_div__DOT__dividend_q;
        IData/*31:0*/ __PVT__u_div__DOT__quotient_q;
        IData/*31:0*/ __PVT__u_div__DOT__q_mask_q;
        IData/*31:0*/ __PVT__u_div__DOT__last_a_q;
        IData/*31:0*/ __PVT__u_div__DOT__last_b_q;
        IData/*31:0*/ __PVT__u_exec0__DOT__imm12_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__alu_input_a_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__alu_input_b_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__result_q;
        IData/*31:0*/ __PVT__u_exec0__DOT__less_than_signed__Vstatic__v;
        IData/*31:0*/ __PVT__u_exec0__DOT__greater_than_signed__Vstatic__v;
        IData/*31:0*/ __PVT__u_exec0__DOT__branch_target_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__pc_x_q;
        IData/*31:0*/ __PVT__u_exec0__DOT__pc_m_q;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__result_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_right_1_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_right_2_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_right_4_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_right_8_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_left_1_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_left_2_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_left_4_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__shift_left_8_r;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__sub_res_w;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__addsub_B;
        IData/*31:0*/ __PVT__u_exec0__DOT__u_alu__DOT__addsub_S;
        IData/*31:0*/ __PVT__u_exec1__DOT__imm12_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__alu_input_a_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__alu_input_b_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__result_q;
        IData/*31:0*/ __PVT__u_exec1__DOT__less_than_signed__Vstatic__v;
        IData/*31:0*/ __PVT__u_exec1__DOT__greater_than_signed__Vstatic__v;
        IData/*31:0*/ __PVT__u_exec1__DOT__branch_target_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__pc_x_q;
        IData/*31:0*/ __PVT__u_exec1__DOT__pc_m_q;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__result_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_right_1_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_right_2_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_right_4_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_right_8_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_left_1_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_left_2_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_left_4_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__shift_left_8_r;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__sub_res_w;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__addsub_B;
        IData/*31:0*/ __PVT__u_exec1__DOT__u_alu__DOT__addsub_S;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__less_than_signed__0__x;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__less_than_signed__0__y;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__greater_than_signed__1__x;
        IData/*31:0*/ __Vfunc_u_exec0__DOT__greater_than_signed__1__y;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__less_than_signed__2__x;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__less_than_signed__2__y;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__greater_than_signed__3__x;
        IData/*31:0*/ __Vfunc_u_exec1__DOT__greater_than_signed__3__y;
    };
    struct {
        IData/*31:0*/ __Vdly__u_div__DOT__dividend_q;
        IData/*31:0*/ __Vdly__u_div__DOT__quotient_q;
        IData/*31:0*/ __Vdly__u_div__DOT__q_mask_q;
        IData/*31:0*/ __Vdly__u_div__DOT__last_a_q;
        IData/*31:0*/ __Vdly__u_div__DOT__last_b_q;
        VL_IN64(__PVT__mem_i_inst_i,63,0);
        QData/*63:0*/ __PVT__u_frontend__DOT__fetch_instr_w;
        QData/*32:0*/ __PVT__u_mul__DOT__operand_a_e1_q;
        QData/*32:0*/ __PVT__u_mul__DOT__operand_b_e1_q;
        QData/*32:0*/ u_mul__DOT____VdfgRegularize_hce0f6733_0_3;
        QData/*62:0*/ __PVT__u_div__DOT__divisor_q;
        QData/*62:0*/ __Vdly__u_div__DOT__divisor_q;
        VlUnpacked<IData/*31:0*/, 8> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__ras_stack_q;
        VlUnpacked<CData/*1:0*/, 512> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__bht_sat_q;
        VlUnpacked<IData/*31:0*/, 32> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_pc_q;
        VlUnpacked<IData/*31:0*/, 32> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_target_q;
        VlUnpacked<CData/*0:0*/, 32> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_call_q;
        VlUnpacked<CData/*0:0*/, 32> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_ret_q;
        VlUnpacked<CData/*0:0*/, 32> __PVT__u_frontend__DOT__u_npc__DOT__BRANCH_PREDICTION__DOT__btb_is_jmp_q;
        VlUnpacked<IData/*31:0*/, 2> __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__pc_q;
        VlUnpacked<CData/*0:0*/, 2> __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__valid0_q;
        VlUnpacked<CData/*0:0*/, 2> __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__valid1_q;
        VlUnpacked<CData/*1:0*/, 2> __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info0_q;
        VlUnpacked<CData/*1:0*/, 2> __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__info1_q;
        VlUnpacked<QData/*63:0*/, 2> __PVT__u_frontend__DOT__u_decode__DOT__genblk1__DOT__u_fifo__DOT__ram_q;
        VlUnpacked<QData/*35:0*/, 2> __PVT__u_lsu__DOT__u_lsu_request__DOT__ram_q;
    };

    // INTERNAL VARIABLES
    Vriscv_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vriscv_top_riscv_core__S1(Vriscv_top__Syms* symsp, const char* v__name);
    ~Vriscv_top_riscv_core__S1();
    VL_UNCOPYABLE(Vriscv_top_riscv_core__S1);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
